
package com.eli.calc.shape.service.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.eli.calc.shape.service.ws.impl.ShapeCalculatorWebServiceImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-15T13:19:33.396-04:00
 * Generated source version: 3.1.7
 * 
 */
public final class ShapeCalculatorWebService_ShapeCalculatorWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.shape.calc.eli.com/", "ShapeCalculatorWebServiceImplService");

    private ShapeCalculatorWebService_ShapeCalculatorWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ShapeCalculatorWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ShapeCalculatorWebServiceImplService ss = new ShapeCalculatorWebServiceImplService(wsdlURL, SERVICE_NAME);
        ShapeCalculatorWebService port = ss.getShapeCalculatorWebServiceImplPort();  
        
        {
        System.out.println("Invoking getPendingRequests...");
        com.eli.calc.shape.service.ws.resp.PendingRequestsResponse _getPendingRequests__return = port.getPendingRequests();
        System.out.println("getPendingRequests.result=" + _getPendingRequests__return);


        }
        {
        System.out.println("Invoking getShapeNames...");
        com.eli.calc.shape.service.ws.resp.ShapeNamesResponse _getShapeNames__return = port.getShapeNames();
        System.out.println("getShapeNames.result=" + _getShapeNames__return);


        }
        {
        System.out.println("Invoking getCalcTypes...");
        com.eli.calc.shape.service.ws.resp.CalcTypesResponse _getCalcTypes__return = port.getCalcTypes();
        System.out.println("getCalcTypes.result=" + _getCalcTypes__return);


        }
        {
        System.out.println("Invoking deletePendingRequests...");
        com.eli.calc.shape.service.ws.resp.StatusResponse _deletePendingRequests__return = port.deletePendingRequests();
        System.out.println("deletePendingRequests.result=" + _deletePendingRequests__return);


        }
        {
        System.out.println("Invoking getCalculatedResults...");
        com.eli.calc.shape.service.ws.resp.CalculatedResultsResponse _getCalculatedResults__return = port.getCalculatedResults();
        System.out.println("getCalculatedResults.result=" + _getCalculatedResults__return);


        }
        {
        System.out.println("Invoking queueCalculation...");
        com.eli.calc.shape.service.ws.parms.QueueCalculationParms _queueCalculation_queueCalculationParms = null;
        com.eli.calc.shape.service.ws.resp.StatusResponse _queueCalculation__return = port.queueCalculation(_queueCalculation_queueCalculationParms);
        System.out.println("queueCalculation.result=" + _queueCalculation__return);


        }
        {
        System.out.println("Invoking deleteResults...");
        com.eli.calc.shape.service.ws.resp.StatusResponse _deleteResults__return = port.deleteResults();
        System.out.println("deleteResults.result=" + _deleteResults__return);


        }
        {
        System.out.println("Invoking runPendingRequestsStopOnError...");
        com.eli.calc.shape.service.ws.resp.RunPendingRequestsResponse _runPendingRequestsStopOnError__return = port.runPendingRequestsStopOnError();
        System.out.println("runPendingRequestsStopOnError.result=" + _runPendingRequestsStopOnError__return);


        }
        {
        System.out.println("Invoking runPendingRequestsNoStopOnError...");
        com.eli.calc.shape.service.ws.resp.RunPendingRequestsResponse _runPendingRequestsNoStopOnError__return = port.runPendingRequestsNoStopOnError();
        System.out.println("runPendingRequestsNoStopOnError.result=" + _runPendingRequestsNoStopOnError__return);


        }

        System.exit(0);
    }

}
